const flashSaleData = [{
        id: 1,
        image: "https://example.com/item1.jpg",
        itemName: "Product 1",
        salePrice: 25.99,
        originalPrice: 39.99,
        ratings: 4.5,
        discountPercentage: 35,
    },
    {
        id: 2,
        image: "https://example.com/item2.jpg",
        itemName: "Product 2",
        salePrice: 19.99,
        originalPrice: 29.99,
        ratings: 4.2,
        discountPercentage: 33,
    },
    {
        id: 3,
        image: "https://example.com/item3.jpg",
        itemName: "Product 3",
        salePrice: 14.99,
        originalPrice: 24.99,
        ratings: 4.0,
        discountPercentage: 40,
    },
    {
        id: 4,
        image: "https://example.com/item4.jpg",
        itemName: "Product 4",
        salePrice: 34.99,
        originalPrice: 49.99,
        ratings: 4.8,
        discountPercentage: 30,
    },
    {
        id: 5,
        image: "https://example.com/item5.jpg",
        itemName: "Product 5",
        salePrice: 22.99,
        originalPrice: 34.99,
        ratings: 4.3,
        discountPercentage: 34,
    },
    {
        id: 6,
        image: "https://example.com/item6.jpg",
        itemName: "Product 6",
        salePrice: 29.99,
        originalPrice: 44.99,
        ratings: 4.6,
        discountPercentage: 33,
    },
    {
        id: 7,
        image: "https://example.com/item7.jpg",
        itemName: "Product 7",
        salePrice: 18.99,
        originalPrice: 29.99,
        ratings: 4.1,
        discountPercentage: 37,
    },
    {
        id: 8,
        image: "https://example.com/item8.jpg",
        itemName: "Product 8",
        salePrice: 27.99,
        originalPrice: 39.99,
        ratings: 4.7,
        discountPercentage: 30,
    },
    {
        id: 9,
        image: "https://example.com/item9.jpg",
        itemName: "Product 9",
        salePrice: 16.99,
        originalPrice: 24.99,
        ratings: 4.2,
        discountPercentage: 32,
    },
    {
        id: 10,
        image: "https://example.com/item10.jpg",
        itemName: "Product 10",
        salePrice: 21.99,
        originalPrice: 31.99,
        ratings: 4.4,
        discountPercentage: 31,
    },
    {
        id: 11,
        image: "https://example.com/item11.jpg",
        itemName: "Product 11",
        salePrice: 32.99,
        originalPrice: 49.99,
        ratings: 4.9,
        discountPercentage: 34,
    },
    {
        id: 12,
        image: "https://example.com/item12.jpg",
        itemName: "Product 12",
        salePrice: 20.99,
        originalPrice: 29.99,
        ratings: 4.0,
        discountPercentage: 30,
    },
    {
        id: 13,
        image: "https://example.com/item13.jpg",
        itemName: "Product 13",
        salePrice: 26.99,
        originalPrice: 39.99,
        ratings: 4.6,
        discountPercentage: 32,
    },
    {
        id: 14,
        image: "https://example.com/item14.jpg",
        itemName: "Product 14",
        salePrice: 18.99,
        originalPrice: 24.99,
        ratings: 4.2,
        discountPercentage: 24,
    },
    {
        id: 15,
        image: "https://example.com/item15.jpg",
        itemName: "Product 15",
        salePrice: 23.99,
        originalPrice: 34.99,
        ratings: 4.7,
        discountPercentage: 31,
    },
    {
        id: 16,
        image: "https://example.com/item16.jpg",
        itemName: "Product 16",
        salePrice: 15.99,
        originalPrice: 21.99,
        ratings: 4.1,
        discountPercentage: 27,
    },
    {
        id: 17,
        image: "https://example.com/item17.jpg",
        itemName: "Product 17",
        salePrice: 28.99,
        originalPrice: 44.99,
        ratings: 4.8,
        discountPercentage: 35,
    },
    {
        id: 18,
        image: "https://example.com/item18.jpg",
        itemName: "Product 18",
        salePrice: 17.99,
        originalPrice: 24.99,
        ratings: 4.5,
        discountPercentage: 28,
    },
    {
        id: 19,
        image: "https://example.com/item19.jpg",
        itemName: "Product 19",
        salePrice: 30.99,
        originalPrice: 39.99,
        ratings: 4.9,
        discountPercentage: 22,
    },
    {
        id: 20,
        image: "https://example.com/item20.jpg",
        itemName: "Product 20",
        salePrice: 19.99,
        originalPrice: 29.99,
        ratings: 4.3,
        discountPercentage: 33,
    },
    {
        id: 21,
        image: "https://example.com/item21.jpg",
        itemName: "Product 21",
        salePrice: 24.99,
        originalPrice: 34.99,
        ratings: 4.6,
        discountPercentage: 29,
    },
    {
        id: 22,
        image: "https://example.com/item22.jpg",
        itemName: "Product 22",
        salePrice: 16.99,
        originalPrice: 24.99,
        ratings: 4.2,
        discountPercentage: 32,
    },
    {
        id: 23,
        image: "https://example.com/item23.jpg",
        itemName: "Product 23",
        salePrice: 22.99,
        originalPrice: 29.99,
        ratings: 4.0,
        discountPercentage: 23,
    },
    {
        id: 24,
        image: "https://example.com/item24.jpg",
        itemName: "Product 24",
        salePrice: 35.99,
        originalPrice: 49.99,
        ratings: 4.7,
        discountPercentage: 28,
    },
    {
        id: 25,
        image: "https://example.com/item25.jpg",
        itemName: "Product 25",
        salePrice: 29.99,
        originalPrice: 39.99,
        ratings: 4.5,
        discountPercentage: 25,
    },
    {
        id: 26,
        image: "https://example.com/item26.jpg",
        itemName: "Product 26",
        salePrice: 18.99,
        originalPrice: 24.99,
        ratings: 4.3,
        discountPercentage: 24,
    },
    {
        id: 27,
        image: "https://example.com/item27.jpg",
        itemName: "Product 27",
        salePrice: 27.99,
        originalPrice: 34.99,
        ratings: 4.1,
        discountPercentage: 20,
    },
    {
        id: 28,
        image: "https://example.com/item28.jpg",
        itemName: "Product 28",
        salePrice: 21.99,
        originalPrice: 29.99,
        ratings: 4.6,
        discountPercentage: 27,
    },
    {
        id: 29,
        image: "https://example.com/item29.jpg",
        itemName: "Product 29",
        salePrice: 23.99,
        originalPrice: 34.99,
        ratings: 4.4,
        discountPercentage: 31,
    },
    {
        id: 30,
        image: "https://example.com/item30.jpg",
        itemName: "Product 30",
        salePrice: 16.99,
        originalPrice: 21.99,
        ratings: 4.2,
        discountPercentage: 23,
    },
];

export default flashSaleData;